language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install:
    - pip install coverage coveralls -e .
script:
    - coverage run --source=imgdiff.py tests.py
after_success:
    - coveralls
notifications:
    email: false
