language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - pypy
    - pypy3
install:
    - pip install coverage coveralls -e .
script:
    - coverage run tests.py
    - coverage report -m --fail-under=100
after_success:
    - coveralls
notifications:
    email: false
cache: pip
